name: Bump new version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn
      - run: |
          echo ${{ github }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          lerna version --conventional-commits --no-push --yes
      - run: git push origin master --follow-tags
      - run: git push origin master:stable
