name: Bump new version

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['CI']
    branches: 'master'
    types: [requested]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn
      - run: lerna version --conventional-commits --no-push --yes
      - run: git push origin master --follow-tags
      - run: git push origin master:stable
